expense_category = {
    'Business': ['FASTSPRING', 'POST BELLEVUE HILL', 'VICTORIASBA', 'KITCHENWARE', 'HYPOP', 'GREATERUNIO',
                 'PAYPAL *ENVATOSTUDI 4029357733 AUS', 'PAYPAL *ENVATO MKPL EN 4029357733 AUS',
                 'PAYPAL *EBAY AU 4029357733 AUS', 'DOCUSIGNINC', 'COFFEEPARTS', 'CIMPRESSAUS', 'CATCHCOMAUP',
                 'AUSTRALIANI', 'APPLIPARTUS', 'ALIPAYSINGA', 'PAESANELLA CHEESE MARRICKVILL AUS', 'T2 APAC Australia',
                 'STAMPED.IO', 'SQUARE AU SUBSCRIP', 'PPSR', 'ZENDESK', 'KAFFAGROUPP',
                 'NSW COURIERS PTY LTD SILVERWATER AUS', 'PAPAS', 'LOTUS STUDIO', 'HARVEY NORMAN', 'GS1 AUSTRALIA',
                 'Freepour Espresso', 'AMAKA', 'aust post', 'bombora', 'MYPOST BUSINESS', 'my post business',
                 'adobesystem', 'Telco', 'Shopify', 'Kennards',
                 'Costco', 'Wheniwork', 'Bob and Petes', 'Fresh Technology', 'Googleaustr', 'InkStation',
                 'AustralianP', 'Godaddy', 'Foodpackagi', 'Officeworks', 'Quillbot', 'Fedder', 'Seek Business',
                 'A1 Restaurant', 'ASIC Sydney', 'Aus Post Online', 'Breeze Valley', 'Bing Lee',
                 'Coffee Tools Distrib', 'FACEBK', 'Fair Trading Licensn', 'ICARE', 'Kounta', 'THEGOODGUYS', 'visy',
                 'typeform', 'Squarespace', 'Teatooptylt', 'Thegoodguys', 'Skype', 'Nisbetsaust', 'new pack',
                 'Bingleeelec', 'Alt Brewing', 'IP Australia'],
    'Grocery': ['SEASIDE FRESH', 'Prime Valley', 'OYSTER COVE FRUIT OYSTER COVE AUS', 'YUBO 20 PTY LTD',
                'NFM CO PTY LTD NOWRA AUS', 'NADER GROUP CONVENIE PENDLE HILL AUS', 'MR. G BUTCHERS PTY',
                'MEAT WORLD EASTWOOD', 'LOLLIES N STUFF WINDSOR', 'SUPERFRESH EASTWOOD', 'HONG PHUOC ONE',
                'HFM PENNANT HILL', 'FAROS BROS PTY LTD', 'EASTWOOD MART', 'woolworth', 'supermarket', 'Coles',
                'New Yen Yen', 'Butchery', 'Deli', 'Blue Fishmonger',
                'Farmers Direct', 'Eastwood Seafood', 'The growers pty ltd ryde', 'Kmall09', 'BWS',
                'C M Fresh Seafood Carlingford', 'Dan Murphy', 'Fresh Asiana', 'Harris Farm', 'Liquorland',
                'WW Metro', 'Xiangyao asian superma'],
    'Lottery': ['POST THORNLEIGH LPO TH', 'THORNLEIGH POST OFFICE', 'Newsagency'],
    'Telcom': ['Vodafone', 'TPG', 'VODAFONEHUT', 'optus', 'Telstra'],
    'Home': ['Spotlight','SLEEPYS HOMEBUSH', 'AMALGAMATED', 'NSW REAL EST THORNLEIGH AUS', 'bunnings', 'ikea', 'Total Tools',
             'Target', 'Taobao'],
    'Subscribe': ['xbox', 'AMZNPRIMEAU', 'Microsoft Ulti', '1Password', 'netflix', 'Nintendo', 'microsoft'],
    'Learning': ['The Art Scene', 'AUSTRALIAN COMMUNICATI BELCONNEN AUS', 'algoexpert', 'Udacity', 'John Wiley',
                 'CA ANZ', 'La trobe', 'Coursra'],
    'Clothing': ['SALVATORE FERRAGAMO', 'ADIDASAUSTR', 'KAKKADU', 'KATHMANDU', 'FOREVER NEW', 'Gazman', 'Lululemon',
                 'Seed', 'Sabre Drummoyne', 'Uniqlo', 'Nike', 'CK Underwear', 'Zara',
                 'Superdry', 'Burberry'],
    'Dine Out': ['SUMMERLAND POINT BAK SUMMERLAND AUS','ZINI CONTEMPORARY Sydney AUS','THE GRAYZING POINT Grays Point AUS','QUEENSIDE','PICKMERE AGRI CON Yoogali AUS','HAWKESBURY RIVER Mooney Moon','GREEN GROVE ORGAN','SOLANNA PTY LTD','SOB MIRANDA TRDNG','SO GOOD EASTWOOD','PLINE PH CARLINGFORD','Shocola Carlingfo', 'SIROO PTY LTD', 'QSR PTY LTD PENNANT HIL AUS', 'Pigeon Whole Bakers',
                 'PICCOLINA HUNTERS', 'Old Town Story Eastwood AUS', 'ON THE RUN PTY LTD LANE COVE AUS',
                 'OCEAN BLUES QUALITY BUDGEWOI AUS', 'KPRSS PTY LTD ERMINGTON', 'Old Town Story', 'CASSIOPEIA COFFEE',
                 'VUM TRADING PL', 'STIX RETAIL PTY LTD', 'SWEET AS KANGAROO', 'Morning Owl',
                 'PICCOLO SPOT CASTLE HILL AUS', 'OLIVER BROWN', 'NPG RETAIL PTY LTD CROYDON AUS', 'Missing Spoon',
                 'Milkwood Bakery', 'MOORILLA ESTATE', 'MONDAY MORNING', 'MCDONALDS', 'Lepain Bakery Turramurra',
                 'LIV*SIP HOUR COFFEE HOMEBUSH', 'KING OF BUNS', 'KANGAROO VALLEY BAKE', 'JIN MEN LI PL EASTWOOD',
                 'JIMMY & ISABELLA', 'JIGGLE CHEESECAKE', 'JC FUTURE NORTH RYDE', 'J AND T BBQ EASTWOOD AUS',
                 'HUAJUN GROUP PTY LTD ASHFIELD', 'GREAT GRAINS', 'GLORIA JEANS', 'GEDIMINAS MUDENAS PADDINGTON AUS',
                 'FLIPPERS COOKED SEAF', 'F2 CORPORATION PTY LTD', 'DRUNKEN ADMIRAL', 'DEFRANCE MIRANDA',
                 'DBENI PTY LIMITED', 'Common Ground Hurstville', 'CAREMAN NOWRA', 'BAY VISTA GATEAU',
                 'ABSOLUTE SERVICES NSW BONDI JUNCT AUS', 'EARLY BIRD EPPING', 'Best Tastes', '21 Grams', 'Cafe',
                 'Seocho', 'Dolcettini', 'Pork rolls', 'Carlingford Court NE', 'Damee', 'Sugarhill',
                 'Smelly Cheesecak', 'Goodwood Bakeshop', 'Aromatic House', 'Hong Kong St Food',
                 'Top Impression Bakery', 'Cherrybrook Bakery', 'Karargy pty ltd', 'Mannus2', 'Wok Inn',
                 'LuneBurger', 'Bare Witness', 'Mels German Bakery', 'Authentic Turkish Paddington',
                 'Brooklyn Boy Bage', 'Gediminas Mudeanas Paddington', 'Gelato', 'Benbry Burger', 'Bonbons Bakry',
                 'Bakerie', 'Burger Urge', 'Chill Bar', 'Cocoa & Bean', 'De Bortoli', 'Frank Restaurant',
                 'Ji Yun Chinese', 'yi xuan pty ltd', 'zinan pty ltd', 'pig & pastry', 'creamery&co', 'Barewitness',
                 'Trappers Bakery', 'Monday Morning Caf', 'Kitchen HBA', 'Silo Espresso', 'Freshwater',
                 'Mini Espresso'],
    'Entertainment': ['Opera', 'Carmen', 'GlenworthOutdoorAdvent', 'Cycleworld Concord'],
    'Digital': ['PAYPAL *HN ONLINE 4029357733 AUS', 'MOBILE FACTORY DIRECT', 'HOMEBUSH JB', 'Apple', 'JB Hi fi',
                'Amazon', 'EB Games', 'mwave'],
    'Insurance': ['INSURANCEAU', 'Allianz', 'Bupa', 'NRMA', 'QBE Insurance'],
    'Transport': ['SILVER SERVIC', 'RYDE TOYOTA', 'uber', 'ENHANCE HOMEBUSH', 'CIRCULAR QUAY SR PL',
                  'CARLINGFORD CAR CARE', '200 TFNSW INTER/IVR SURRY HILLS AUS', 'Petrol', 'Speedw', 'Opal',
                  'Service NSW', 'Franks Automotive', 'North Shore Hi-tech',
                  'Medco Carlingford', 'Ampol', 'Metro Ryde', 'EG Group', 'Unigas', '7-Eleven', 'BP', 'Caltex',
                  'KMART Tyre', 'Lidcombe Service', 'mycar', 'United Yagoona', 'Transportfornsw', 'TDP Fuels',
                  'Sealink'],
    'Daily': ['THE ICONIC', 'SPOTLIGHTPT', 'SLEEPSOLNS', 'PAYPAL *HUTCOMLIMIT 4029357733 AUS', 'Interest Charges',
              'PANDORA', 'SEPHORA', 'SephoraAU', 'Kiehlsau', 'Typo 2743 Macquarie', 'Mecca', 'Daojia', 'Pharmacy',
              'Lancomeau'], 'Utility': ['AGL'],
    'Health': ['DR STEPHEN PAK', 'Chemist warehouse', 'CWH PENNANT HILLS'],
    'Parking': ['SYDNEYAIRPO', 'NBC-PAY & DISPLAY PARK DEE WHY AUS', 'LIDCOMBE SHOP CENTRE',
                'Waverley Council Bondi Junct', 'Council Parki North Sydne', 'Cityofsydney parking',
                'Cumberland Council Auburn', 'wilson parking'],
    'Pet': ['Pet Circle', 'Petcultureg', 'Catevolution'],
    'Travel': ['PORT ARTHUR HISTORIC S PORT ARTHUR AUS', 'TENTWORLD', 'KOOKOOTONGA NUT', 'TARONGA CONSERVATION',
               'NPWS ENTRY PASS Parramatta AUS', 'Mona - Events', 'MUSEUM OF OLD AND NEW BERRIEDALE', 'ANACONDA',
               'CampingAcco', '123 TIX DUBBO AUS', 'Hertz', 'Bruny Island', 'Crowne Plaza', 'Western plains zoo dubbo'],
    'Fitness': ['Anytime Fitness', 'Decathlon', 'Fitness Chullora']}


def findExpenseCategory(supplier):
    for key, value in expense_category.items():
        for item in value:
            if item.lower() in supplier.lower():
                return key
